import { NewsArticle } from "../NewsArticle";

export const DEFAULT_NEWS_ARTICLES = [
    new NewsArticle(
        "Revolutionizing Waste Management: The Rise of Smart Recycling Bins",
        "bg-recycling",
        [
            "In recent years, the world has witnessed a significant shift towards eco-friendliness and sustainable living. As the global community becomes increasingly aware of the environmental impact of waste, innovative solutions are emerging to revolutionize waste management practices. One such solution taking center stage is the advent of smart recycling bins.",
            "Smart recycling bins, powered by cutting-edge technology, are transforming the way we recycle and contribute to a greener future. These intelligent bins combine advanced sensors, connectivity, and data analytics to optimize recycling efforts and encourage responsible waste disposal.",
            "The key feature of smart recycling bins is their ability to sort and categorize different types of waste automatically. Equipped with sensors, these bins can identify and separate recyclable materials, such as plastic, paper, glass, and metal, from general waste. This streamlines the recycling process and minimizes contamination, ensuring that each recyclable item reaches the appropriate recycling facility.",
            "But the innovation doesn't stop there. Smart recycling bins are also integrated with real-time data monitoring systems. This enables waste management authorities and individuals to track waste levels, identify collection schedules, and optimize collection routes. By leveraging data-driven insights, these bins contribute to more efficient waste management practices, reducing costs and carbon emissions associated with unnecessary pickups.",
            "Furthermore, smart recycling bins are designed with user convenience in mind. Many of them feature touchless operation, allowing users to open the bin using motion sensors or foot pedals, promoting hygiene and preventing the spread of germs. Some models even incorporate gamification elements, rewarding users for recycling correctly and encouraging sustainable habits.",
            "The rise of smart recycling bins signifies a new era in waste management, one where technology and environmental consciousness converge. These bins not only simplify the recycling process for individuals but also empower waste management authorities with valuable insights to optimize operations and reduce environmental impact.",
            "Companies like Bintendo are at the forefront of this movement, offering a wide range of smart recycling bins to cater to various needs and preferences. As more individuals and organizations embrace these innovative solutions, the collective impact on global sustainability can be truly transformative.",
            "So, whether you are an environmentally conscious homeowner or a waste management professional seeking efficient recycling solutions, keep an eye on the rising trend of smart recycling bins. Together, we can shape a future where waste becomes a valuable resource and sustainable practices become the norm.",
        ]
    ),
    new NewsArticle(
        "Confronting the Great Pacific Garbage Patch: A Call to Action for Ocean Conservation",
        "bg-beach-trash",
        [
            "The world's oceans, known for their vast beauty and remarkable biodiversity, are facing an escalating threat—the Great Pacific Garbage Patch. Spanning millions of square kilometers in the North Pacific Ocean, this massive accumulation of floating debris has captured global attention and sparked an urgent call for action.",
            "The Great Pacific Garbage Patch is a testament to the consequences of excessive plastic consumption and improper waste management. It is estimated to contain over 1.8 trillion pieces of plastic, weighing approximately 80,000 metric tons. The patch poses severe threats to marine life, ecosystems, and the overall health of our planet.",
            "Marine creatures often mistake plastic debris for food, leading to entanglement, suffocation, and starvation. The ingestion of microplastics by fish and other marine species has also raised concerns about potential impacts on human health through the seafood we consume. Furthermore, the presence of plastic debris disrupts natural oceanic processes, affecting nutrient cycles and the delicate balance of marine ecosystems.",
            "To address this pressing environmental crisis, collective efforts are needed at every level—individuals, communities, industries, and governments. Companies like Bintendo are taking a proactive stance by promoting sustainable waste management practices and offering eco-friendly solutions.",
            "Reducing plastic consumption and implementing responsible waste disposal practices are crucial steps towards mitigating the Great Pacific Garbage Patch. Recycling and reusing plastics, opting for biodegradable alternatives, and supporting initiatives that encourage plastic waste reduction are practical ways individuals can contribute to the cause.",
            "Education and awareness play a pivotal role in combating the issue. Bintendo is committed to raising awareness about the Great Pacific Garbage Patch and ocean conservation through initiatives such as educational campaigns, partnerships with environmental organizations, and supporting research efforts aimed at finding innovative solutions.",
            "Furthermore, governments and policymakers play a critical role in addressing this environmental crisis. Implementing stricter regulations on single-use plastics, promoting extended producer responsibility, and investing in recycling infrastructure are essential steps towards tackling the problem at its source.",
            "Collaboration among nations is paramount to combating the Great Pacific Garbage Patch. International agreements and partnerships focused on marine debris management, such as the United Nations' Clean Seas campaign, provide a platform for joint action and knowledge-sharing.",
            "The road ahead may seem challenging, but with collective determination, we can make a difference. By supporting organizations like Bintendo and joining the global movement to reduce plastic waste, we can work towards restoring the health of our oceans and preserving their beauty for future generations.",
            "The Great Pacific Garbage Patch serves as a stark reminder that the choices we make today will shape the future of our planet. Together, let us confront this environmental challenge head-on and build a world where our oceans thrive, free from the grip of plastic pollution.",
        ]
    ),
    new NewsArticle("News 2", "bg-wes-bins", [
        "In recent years, the world has witnessed a significant shift towards eco-friendliness and sustainable living. As the global community becomes increasingly aware of the environmental impact of waste, innovative solutions are emerging to revolutionize waste management practices. One such solution taking center stage is the advent of smart recycling bins.",
        "Smart recycling bins, powered by cutting-edge technology, are transforming the way we recycle and contribute to a greener future. These intelligent bins combine advanced sensors, connectivity, and data analytics to optimize recycling efforts and encourage responsible waste disposal.",
        "The key feature of smart recycling bins is their ability to sort and categorize different types of waste automatically. Equipped with sensors, these bins can identify and separate recyclable materials, such as plastic, paper, glass, and metal, from general waste. This streamlines the recycling process and minimizes contamination, ensuring that each recyclable item reaches the appropriate recycling facility.",
        "But the innovation doesn't stop there. Smart recycling bins are also integrated with real-time data monitoring systems. This enables waste management authorities and individuals to track waste levels, identify collection schedules, and optimize collection routes. By leveraging data-driven insights, these bins contribute to more efficient waste management practices, reducing costs and carbon emissions associated with unnecessary pickups.",
        "Furthermore, smart recycling bins are designed with user convenience in mind. Many of them feature touchless operation, allowing users to open the bin using motion sensors or foot pedals, promoting hygiene and preventing the spread of germs. Some models even incorporate gamification elements, rewarding users for recycling correctly and encouraging sustainable habits.",
        "The rise of smart recycling bins signifies a new era in waste management, one where technology and environmental consciousness converge. These bins not only simplify the recycling process for individuals but also empower waste management authorities with valuable insights to optimize operations and reduce environmental impact.",
        "Companies like Bintendo are at the forefront of this movement, offering a wide range of smart recycling bins to cater to various needs and preferences. As more individuals and organizations embrace these innovative solutions, the collective impact on global sustainability can be truly transformative.",
        "So, whether you are an environmentally conscious homeowner or a waste management professional seeking efficient recycling solutions, keep an eye on the rising trend of smart recycling bins. Together, we can shape a future where waste becomes a valuable resource and sustainable practices become the norm.",
    ]),
    new NewsArticle("News 3", "bg-garbage-truck", [
        "In recent years, the world has witnessed a significant shift towards eco-friendliness and sustainable living. As the global community becomes increasingly aware of the environmental impact of waste, innovative solutions are emerging to revolutionize waste management practices. One such solution taking center stage is the advent of smart recycling bins.",
        "Smart recycling bins, powered by cutting-edge technology, are transforming the way we recycle and contribute to a greener future. These intelligent bins combine advanced sensors, connectivity, and data analytics to optimize recycling efforts and encourage responsible waste disposal.",
        "The key feature of smart recycling bins is their ability to sort and categorize different types of waste automatically. Equipped with sensors, these bins can identify and separate recyclable materials, such as plastic, paper, glass, and metal, from general waste. This streamlines the recycling process and minimizes contamination, ensuring that each recyclable item reaches the appropriate recycling facility.",
        "But the innovation doesn't stop there. Smart recycling bins are also integrated with real-time data monitoring systems. This enables waste management authorities and individuals to track waste levels, identify collection schedules, and optimize collection routes. By leveraging data-driven insights, these bins contribute to more efficient waste management practices, reducing costs and carbon emissions associated with unnecessary pickups.",
        "Furthermore, smart recycling bins are designed with user convenience in mind. Many of them feature touchless operation, allowing users to open the bin using motion sensors or foot pedals, promoting hygiene and preventing the spread of germs. Some models even incorporate gamification elements, rewarding users for recycling correctly and encouraging sustainable habits.",
        "The rise of smart recycling bins signifies a new era in waste management, one where technology and environmental consciousness converge. These bins not only simplify the recycling process for individuals but also empower waste management authorities with valuable insights to optimize operations and reduce environmental impact.",
        "Companies like Bintendo are at the forefront of this movement, offering a wide range of smart recycling bins to cater to various needs and preferences. As more individuals and organizations embrace these innovative solutions, the collective impact on global sustainability can be truly transformative.",
        "So, whether you are an environmentally conscious homeowner or a waste management professional seeking efficient recycling solutions, keep an eye on the rising trend of smart recycling bins. Together, we can shape a future where waste becomes a valuable resource and sustainable practices become the norm.",
    ]),
    new NewsArticle("News 4", "bg-wes-bins", [
        "In recent years, the world has witnessed a significant shift towards eco-friendliness and sustainable living. As the global community becomes increasingly aware of the environmental impact of waste, innovative solutions are emerging to revolutionize waste management practices. One such solution taking center stage is the advent of smart recycling bins.",
        "Smart recycling bins, powered by cutting-edge technology, are transforming the way we recycle and contribute to a greener future. These intelligent bins combine advanced sensors, connectivity, and data analytics to optimize recycling efforts and encourage responsible waste disposal.",
        "The key feature of smart recycling bins is their ability to sort and categorize different types of waste automatically. Equipped with sensors, these bins can identify and separate recyclable materials, such as plastic, paper, glass, and metal, from general waste. This streamlines the recycling process and minimizes contamination, ensuring that each recyclable item reaches the appropriate recycling facility.",
        "But the innovation doesn't stop there. Smart recycling bins are also integrated with real-time data monitoring systems. This enables waste management authorities and individuals to track waste levels, identify collection schedules, and optimize collection routes. By leveraging data-driven insights, these bins contribute to more efficient waste management practices, reducing costs and carbon emissions associated with unnecessary pickups.",
        "Furthermore, smart recycling bins are designed with user convenience in mind. Many of them feature touchless operation, allowing users to open the bin using motion sensors or foot pedals, promoting hygiene and preventing the spread of germs. Some models even incorporate gamification elements, rewarding users for recycling correctly and encouraging sustainable habits.",
        "The rise of smart recycling bins signifies a new era in waste management, one where technology and environmental consciousness converge. These bins not only simplify the recycling process for individuals but also empower waste management authorities with valuable insights to optimize operations and reduce environmental impact.",
        "Companies like Bintendo are at the forefront of this movement, offering a wide range of smart recycling bins to cater to various needs and preferences. As more individuals and organizations embrace these innovative solutions, the collective impact on global sustainability can be truly transformative.",
        "So, whether you are an environmentally conscious homeowner or a waste management professional seeking efficient recycling solutions, keep an eye on the rising trend of smart recycling bins. Together, we can shape a future where waste becomes a valuable resource and sustainable practices become the norm.",
    ]),
    new NewsArticle("News 6", "bg-wes-bins", [
        "In recent years, the world has witnessed a significant shift towards eco-friendliness and sustainable living. As the global community becomes increasingly aware of the environmental impact of waste, innovative solutions are emerging to revolutionize waste management practices. One such solution taking center stage is the advent of smart recycling bins.",
        "Smart recycling bins, powered by cutting-edge technology, are transforming the way we recycle and contribute to a greener future. These intelligent bins combine advanced sensors, connectivity, and data analytics to optimize recycling efforts and encourage responsible waste disposal.",
        "The key feature of smart recycling bins is their ability to sort and categorize different types of waste automatically. Equipped with sensors, these bins can identify and separate recyclable materials, such as plastic, paper, glass, and metal, from general waste. This streamlines the recycling process and minimizes contamination, ensuring that each recyclable item reaches the appropriate recycling facility.",
        "But the innovation doesn't stop there. Smart recycling bins are also integrated with real-time data monitoring systems. This enables waste management authorities and individuals to track waste levels, identify collection schedules, and optimize collection routes. By leveraging data-driven insights, these bins contribute to more efficient waste management practices, reducing costs and carbon emissions associated with unnecessary pickups.",
        "Furthermore, smart recycling bins are designed with user convenience in mind. Many of them feature touchless operation, allowing users to open the bin using motion sensors or foot pedals, promoting hygiene and preventing the spread of germs. Some models even incorporate gamification elements, rewarding users for recycling correctly and encouraging sustainable habits.",
        "The rise of smart recycling bins signifies a new era in waste management, one where technology and environmental consciousness converge. These bins not only simplify the recycling process for individuals but also empower waste management authorities with valuable insights to optimize operations and reduce environmental impact.",
        "Companies like Bintendo are at the forefront of this movement, offering a wide range of smart recycling bins to cater to various needs and preferences. As more individuals and organizations embrace these innovative solutions, the collective impact on global sustainability can be truly transformative.",
        "So, whether you are an environmentally conscious homeowner or a waste management professional seeking efficient recycling solutions, keep an eye on the rising trend of smart recycling bins. Together, we can shape a future where waste becomes a valuable resource and sustainable practices become the norm.",
    ]),
];

export const getNewsArticleById = (id: number) => {
    return DEFAULT_NEWS_ARTICLES.find(
        (newsArticle: NewsArticle) => newsArticle.newsArticleId === id
    );
};
