import { NewsArticle } from "../NewsArticle";

export const DEFAULT_NEWS_ARTICLES = [
    new NewsArticle(
        "Revolutionizing Waste Management: The Rise of Smart Recycling Bins",
        "bg-recycling",
        [
            "In recent years, the world has witnessed a significant shift towards eco-friendliness and sustainable living. As the global community becomes increasingly aware of the environmental impact of waste, innovative solutions are emerging to revolutionize waste management practices. One such solution taking center stage is the advent of smart recycling bins.",
            "Smart recycling bins, powered by cutting-edge technology, are transforming the way we recycle and contribute to a greener future. These intelligent bins combine advanced sensors, connectivity, and data analytics to optimize recycling efforts and encourage responsible waste disposal.",
            "The key feature of smart recycling bins is their ability to sort and categorize different types of waste automatically. Equipped with sensors, these bins can identify and separate recyclable materials, such as plastic, paper, glass, and metal, from general waste. This streamlines the recycling process and minimizes contamination, ensuring that each recyclable item reaches the appropriate recycling facility.",
            "But the innovation doesn't stop there. Smart recycling bins are also integrated with real-time data monitoring systems. This enables waste management authorities and individuals to track waste levels, identify collection schedules, and optimize collection routes. By leveraging data-driven insights, these bins contribute to more efficient waste management practices, reducing costs and carbon emissions associated with unnecessary pickups.",
            "Furthermore, smart recycling bins are designed with user convenience in mind. Many of them feature touchless operation, allowing users to open the bin using motion sensors or foot pedals, promoting hygiene and preventing the spread of germs. Some models even incorporate gamification elements, rewarding users for recycling correctly and encouraging sustainable habits.",
            "The rise of smart recycling bins signifies a new era in waste management, one where technology and environmental consciousness converge. These bins not only simplify the recycling process for individuals but also empower waste management authorities with valuable insights to optimize operations and reduce environmental impact.",
            "Companies like Bintendo are at the forefront of this movement, offering a wide range of smart recycling bins to cater to various needs and preferences. As more individuals and organizations embrace these innovative solutions, the collective impact on global sustainability can be truly transformative.",
            "So, whether you are an environmentally conscious homeowner or a waste management professional seeking efficient recycling solutions, keep an eye on the rising trend of smart recycling bins. Together, we can shape a future where waste becomes a valuable resource and sustainable practices become the norm.",
        ]
    ),
    new NewsArticle("News 2", "bg-wes-bins", [
        "In recent years, the world has witnessed a significant shift towards eco-friendliness and sustainable living. As the global community becomes increasingly aware of the environmental impact of waste, innovative solutions are emerging to revolutionize waste management practices. One such solution taking center stage is the advent of smart recycling bins.",
        "Smart recycling bins, powered by cutting-edge technology, are transforming the way we recycle and contribute to a greener future. These intelligent bins combine advanced sensors, connectivity, and data analytics to optimize recycling efforts and encourage responsible waste disposal.",
        "The key feature of smart recycling bins is their ability to sort and categorize different types of waste automatically. Equipped with sensors, these bins can identify and separate recyclable materials, such as plastic, paper, glass, and metal, from general waste. This streamlines the recycling process and minimizes contamination, ensuring that each recyclable item reaches the appropriate recycling facility.",
        "But the innovation doesn't stop there. Smart recycling bins are also integrated with real-time data monitoring systems. This enables waste management authorities and individuals to track waste levels, identify collection schedules, and optimize collection routes. By leveraging data-driven insights, these bins contribute to more efficient waste management practices, reducing costs and carbon emissions associated with unnecessary pickups.",
        "Furthermore, smart recycling bins are designed with user convenience in mind. Many of them feature touchless operation, allowing users to open the bin using motion sensors or foot pedals, promoting hygiene and preventing the spread of germs. Some models even incorporate gamification elements, rewarding users for recycling correctly and encouraging sustainable habits.",
        "The rise of smart recycling bins signifies a new era in waste management, one where technology and environmental consciousness converge. These bins not only simplify the recycling process for individuals but also empower waste management authorities with valuable insights to optimize operations and reduce environmental impact.",
        "Companies like Bintendo are at the forefront of this movement, offering a wide range of smart recycling bins to cater to various needs and preferences. As more individuals and organizations embrace these innovative solutions, the collective impact on global sustainability can be truly transformative.",
        "So, whether you are an environmentally conscious homeowner or a waste management professional seeking efficient recycling solutions, keep an eye on the rising trend of smart recycling bins. Together, we can shape a future where waste becomes a valuable resource and sustainable practices become the norm.",
    ]),
    new NewsArticle("News 3", "bg-garbage-truck", [
        "In recent years, the world has witnessed a significant shift towards eco-friendliness and sustainable living. As the global community becomes increasingly aware of the environmental impact of waste, innovative solutions are emerging to revolutionize waste management practices. One such solution taking center stage is the advent of smart recycling bins.",
        "Smart recycling bins, powered by cutting-edge technology, are transforming the way we recycle and contribute to a greener future. These intelligent bins combine advanced sensors, connectivity, and data analytics to optimize recycling efforts and encourage responsible waste disposal.",
        "The key feature of smart recycling bins is their ability to sort and categorize different types of waste automatically. Equipped with sensors, these bins can identify and separate recyclable materials, such as plastic, paper, glass, and metal, from general waste. This streamlines the recycling process and minimizes contamination, ensuring that each recyclable item reaches the appropriate recycling facility.",
        "But the innovation doesn't stop there. Smart recycling bins are also integrated with real-time data monitoring systems. This enables waste management authorities and individuals to track waste levels, identify collection schedules, and optimize collection routes. By leveraging data-driven insights, these bins contribute to more efficient waste management practices, reducing costs and carbon emissions associated with unnecessary pickups.",
        "Furthermore, smart recycling bins are designed with user convenience in mind. Many of them feature touchless operation, allowing users to open the bin using motion sensors or foot pedals, promoting hygiene and preventing the spread of germs. Some models even incorporate gamification elements, rewarding users for recycling correctly and encouraging sustainable habits.",
        "The rise of smart recycling bins signifies a new era in waste management, one where technology and environmental consciousness converge. These bins not only simplify the recycling process for individuals but also empower waste management authorities with valuable insights to optimize operations and reduce environmental impact.",
        "Companies like Bintendo are at the forefront of this movement, offering a wide range of smart recycling bins to cater to various needs and preferences. As more individuals and organizations embrace these innovative solutions, the collective impact on global sustainability can be truly transformative.",
        "So, whether you are an environmentally conscious homeowner or a waste management professional seeking efficient recycling solutions, keep an eye on the rising trend of smart recycling bins. Together, we can shape a future where waste becomes a valuable resource and sustainable practices become the norm.",
    ]),
    new NewsArticle("News 4", "bg-wes-bins", [
        "In recent years, the world has witnessed a significant shift towards eco-friendliness and sustainable living. As the global community becomes increasingly aware of the environmental impact of waste, innovative solutions are emerging to revolutionize waste management practices. One such solution taking center stage is the advent of smart recycling bins.",
        "Smart recycling bins, powered by cutting-edge technology, are transforming the way we recycle and contribute to a greener future. These intelligent bins combine advanced sensors, connectivity, and data analytics to optimize recycling efforts and encourage responsible waste disposal.",
        "The key feature of smart recycling bins is their ability to sort and categorize different types of waste automatically. Equipped with sensors, these bins can identify and separate recyclable materials, such as plastic, paper, glass, and metal, from general waste. This streamlines the recycling process and minimizes contamination, ensuring that each recyclable item reaches the appropriate recycling facility.",
        "But the innovation doesn't stop there. Smart recycling bins are also integrated with real-time data monitoring systems. This enables waste management authorities and individuals to track waste levels, identify collection schedules, and optimize collection routes. By leveraging data-driven insights, these bins contribute to more efficient waste management practices, reducing costs and carbon emissions associated with unnecessary pickups.",
        "Furthermore, smart recycling bins are designed with user convenience in mind. Many of them feature touchless operation, allowing users to open the bin using motion sensors or foot pedals, promoting hygiene and preventing the spread of germs. Some models even incorporate gamification elements, rewarding users for recycling correctly and encouraging sustainable habits.",
        "The rise of smart recycling bins signifies a new era in waste management, one where technology and environmental consciousness converge. These bins not only simplify the recycling process for individuals but also empower waste management authorities with valuable insights to optimize operations and reduce environmental impact.",
        "Companies like Bintendo are at the forefront of this movement, offering a wide range of smart recycling bins to cater to various needs and preferences. As more individuals and organizations embrace these innovative solutions, the collective impact on global sustainability can be truly transformative.",
        "So, whether you are an environmentally conscious homeowner or a waste management professional seeking efficient recycling solutions, keep an eye on the rising trend of smart recycling bins. Together, we can shape a future where waste becomes a valuable resource and sustainable practices become the norm.",
    ]),
];

export const getNewsArticleById = (id: number) => {
    return DEFAULT_NEWS_ARTICLES.find(
        (newsArticle: NewsArticle) => newsArticle.newsArticleId === id
    );
};
